name: fortys-bot-dev
services:
  db:
    image: postgres:12-alpine
    restart: always
    networks:
      - server-side
    environment:
      - POSTGRES_USER=fortys-bot-dev
      - POSTGRES_PASSWORD=fortys-bot-dev
      - POSTGRES_DB=fortys-bot-dev
    ports:
      - '5432:5432'
    volumes:
      - ./data/db:/var/lib/postgresql/data
  bot:
    build: .
    networks:
      - server-side
    depends_on:
      - db
    working_dir: /usr/src/app
    volumes:
      - ./:/usr/src/app
    command: ['pm2-dev', './build/server.js']
networks:
  server-side: {}
