# fly.toml app configuration file generated for 40percent-bot-staging on 2023-11-01T14:34:10-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "40percent-bot-staging"
primary_region = "ewr"

[build]
