name: Node CI

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

env:
  CARGO_TERM_COLOR: always
  NODE_ENV: test

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: '18.18.0'

      - run: npm ci --include=dev

      - uses: tj-actions/eslint-changed-files@v21
        with:
          config_path: ".eslintrc.json"

  prettier:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '18.18.0'

      - run: npm ci --include=dev

      - run: npx prettier 'src/**/*.ts' --check --config .prettierrc.json

  test:
    runs-on: ubuntu-latest
    name: Test
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: '18.18.0'
      - run: npm ci --include=dev
      - run: npm run build --if-present
      - run: npm test

  deploy-staging:
    name: Deploy staging
    needs: test
    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
    uses: ./.github/workflows/deploy.yml
    with:
      fly_env: 40percent-bot-staging
    secrets: inherit

  deploy-prod:
    name: Deploy prod
    needs: deploy-staging
    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
    uses: ./.github/workflows/deploy.yml
    with:
      fly_env: 40percent-bot-prod
    secrets: inherit
